In [64]:
import pandas as pd

# Carregamento dos dados
acidentes = pd.read_csv('./acidentes/acidentes_2022.csv')
localidades = pd.read_csv('./localidades/localidades_2022.csv')
tipo_veiculo = pd.read_csv('./tipo_veiculo/tipo_veiculo_2022.csv', sep=';')
vitimas = pd.read_csv('./vitimas/vitimas_2022.csv')

acidentes_ro = acidentes[acidentes['uf_acidente'] == 'RO']
localidades_ro = localidades[localidades['uf'] == 'RO']
vitimas_ro = vitimas[vitimas['uf_acidente'] == 'RO']

/tmp/ipykernel_29621/459157943.py:4: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  acidentes = pd.read_csv('./acidentes/acidentes_2022.csv')

In [2]:
# Carregamento dos dados
acidentes.head(100)

,Unnamed: 0,num_acidente,chv_localidade,data_acidente,uf_acidente,ano_acidente,mes_acidente,mes_ano_acidente,faixa_idade,genero,tp_envolvido,gravidade_lesao,equip_seguranca,ind_motorista,susp_alcool,qtde_envolvidos,qtde_feridosilesos,qtde_obitos
0,31977,4231902,AC1200401202201,2022-01-28,AC,2022,1,12022,ENTRE 18 E 24 ANOS,MASCULINO,MOTORISTA,NAO INFORMADO,NAO INFORMADO,SIM,NAO INFORMADO,1,1,0
1,31978,1889037,AC1200401202201,2022-01-08,AC,2022,1,12022,NAO INFORMADO,NAO INFORMADO,MOTORISTA,NAO INFORMADO,NAO INFORMADO,SIM,NAO INFORMADO,1,1,0
2,31979,546476,AC1200104202201,2022-01-21,AC,2022,1,12022,NAO INFORMADO,MASCULINO,MOTORISTA,NAO INFORMADO,NAO INFORMADO,SIM,NAO INFORMADO,1,1,0
3,31980,1979621,AC1200609202201,2022-01-16,AC,2022,1,12022,NAO INFORMADO,MASCULINO,MOTORISTA,NAO INFORMADO,NAO INFORMADO,SIM,NAO,1,1,0
4,31981,1752444,AC1200807202201,2022-01-19,AC,2022,1,12022,NAO INFORMADO,FEMININO,MOTORISTA,NAO INFORMADO,NAO INFORMADO,SIM,NAO INFORMADO,1,1,0

In [3]:
localidades.head(100)

,Unnamed: 0,chv_localidade,ano_referencia,mes_referencia,mes_ano_referencia,regiao,uf,codigo_ibge,municipio,regiao_metropolitana,qtde_habitantes,frota_total,frota_circulante
0,1104,AC1200393202201,2022,1,12022,NORTE,AC,1200393,PORTO WALTER,nao,12497,394,295
1,1105,AC1200179202201,2022,1,12022,NORTE,AC,1200179,CAPIXABA,nao,12280,2677,2058
2,1106,AC1200328202201,2022,1,12022,NORTE,AC,1200328,JORDAO,nao,8628,147,95
3,1107,AC1200450202201,2022,1,12022,NORTE,AC,1200450,SENADOR GUIOMARD,nao,23446,7634,5836
4,1108,AC1200609202201,2022,1,12022,NORTE,AC,1200609,TARAUACA,nao,43730,5406,4390
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1199,AC0000000202205,2022,5,52022,NORTE,AC,0,NAO INFORMADO,nao,0,0,0
96,1200,AC1200500202205,2022,5,52022,NORTE,AC,1200500,SENA MADUREIRA,nao,47562,10106,8315
97,1201,AC1200054202205,2022,5,52022,NORTE,AC,1200054,ASSIS BRASIL,nao,7713,2162,1727
98,1202,AC1200385202205,2022,5,52022,NORTE,AC,1200385,PLACIDO DE CASTRO,nao,20313,5462,4157
99,1203,AC1200807202205,2022,5,52022,NORTE,AC,1200807,PORTO ACRE,nao,19302,4433,3351

In [4]:
tipo_veiculo.head(100)

    num_acidente   tipo_veiculo ind_veic_estrangeiro  qtde_veiculos
0             57  NAO INFORMADO        NAO INFORMADO              1
1             76  NAO INFORMADO        NAO INFORMADO              1
2            241  NAO INFORMADO        NAO INFORMADO              1
3            470  NAO INFORMADO        NAO INFORMADO              1
4            549  NAO INFORMADO        NAO INFORMADO              1
..           ...            ...                  ...            ...
95          3855  NAO INFORMADO        NAO INFORMADO              2
96          3889  NAO INFORMADO        NAO INFORMADO              3
97          3909  NAO INFORMADO        NAO INFORMADO              1
98          4132  NAO INFORMADO        NAO INFORMADO              1
99          4134  NAO INFORMADO        NAO INFORMADO              2

[100 rows x 4 columns]

In [5]:
acidentes.head(100)

,Unnamed: 0,num_acidente,chv_localidade,data_acidente,uf_acidente,ano_acidente,mes_acidente,mes_ano_acidente,codigo_ibge,dia_semana,...,lim_velocidade,tp_pista,ind_guardrail,ind_cantcentral,ind_acostamento,qtde_acidente,qtde_acid_com_obitos,qtde_envolvidos,qtde_feridosilesos,qtde_obitos
0,16027,1676690,AC1200401202201,2022-01-21,AC,2022,1,12022,1200401,SEXTA-FEIRA,...,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,1,0,1,1,0
1,16028,4441865,AC1200401202201,2022-01-03,AC,2022,1,12022,1200401,SEGUNDA-FEIRA,...,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,1,0,2,2,0
2,16029,3797599,AC1200401202201,2022-01-20,AC,2022,1,12022,1200401,QUINTA-FEIRA,...,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,1,0,2,2,0
3,16030,2339226,AC1200401202201,2022-01-23,AC,2022,1,12022,1200401,DOMINGO,...,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,1,0,3,3,0
4,16031,3838808,AC1200401202201,2022-01-12,AC,2022,1,12022,1200401,QUARTA-FEIRA,...,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,1,0,2,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,16122,291284,AC1200401202201,2022-01-04,AC,2022,1,12022,1200401,TERCA-FEIRA,...,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,1,0,2,2,0
96,16123,2926727,AC1200401202201,2022-01-17,AC,2022,1,12022,1200401,SEGUNDA-FEIRA,...,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,1,0,2,2,0
97,16124,89130,AC1200401202201,2022-01-15,AC,2022,1,12022,1200401,SABADO,...,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,1,0,1,1,0
98,16125,3244169,AC1200104202201,2022-01-12,AC,2022,1,12022,1200104,QUARTA-FEIRA,...,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,1,0,2,2,0
99,16126,2207590,AC1200401202201,2022-01-01,AC,2022,1,12022,1200401,SABADO,...,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,NAO INFORMADO,1,0,2,2,0

In [73]:
## Quais cidades de RO apresentaram mais acidentes em 2022 em valores absolutos?
pd.merge(acidentes_ro, localidades_ro, left_on='chv_localidade', right_on='chv_localidade', how='left')[['num_acidente', 'municipio']].groupby('municipio').count().sort_values(by='num_acidente', ascending=False)

                           num_acidente
municipio
PORTO VELHO                        5592
JI-PARANA                          1374
VILHENA                            1330
CACOAL                              971
ARIQUEMES                           966
ROLIM DE MOURA                      696
JARU                                449
PIMENTA BUENO                       405
ESPIGAO D OESTE                     266
OURO PRETO DO OESTE                 263
GUAJARA-MIRIM                       185
MACHADINHO D OESTE                  175
ALTA FLORESTA D OESTE               174
SAO MIGUEL DO GUAPORE               158
BURITIS                             143
CANDEIAS DO JAMARI                  143
CEREJEIRAS                          127
PRESIDENTE MEDICI                   115
COLORADO DO OESTE                   102
SAO FRANCISCO DO GUAPORE             99
NOVA BRASILANDIA D OESTE             95
ALVORADA D OESTE                     94
CUJUBIM                              93
ALTO PARAISO                         82
NOVA MAMORE                          82
ITAPUA DO OESTE                      71
COSTA MARQUES                        60
ALTO ALEGRE DOS PARECIS              59
MONTE NEGRO                          57
CHUPINGUAIA                          56
THEOBROMA                            54
CORUMBIARA                           53
SERINGUEIRAS                         47
SANTA LUZIA D OESTE                  47
MIRANTE DA SERRA                     46
NOVO HORIZONTE DO OESTE              44
URUPA                                37
VALE DO ANARI                        32
SAO FELIPE D OESTE                   31
NOVA UNIAO                           31
MINISTRO ANDREAZZA                   30
TEIXEIROPOLIS                        25
VALE DO PARAISO                      24
CABIXI                               22
PRIMAVERA DE RONDONIA                22
GOVERNADOR JORGE TEIXEIRA            22
CAMPO NOVO DE RONDONIA               21
PARECIS                              15
RIO CRESPO                           14
PIMENTEIRAS DO OESTE                 12
CASTANHEIRAS                         11
CACAULANDIA                           9

In [66]:
# Qual a média de acidentes a cada mil habitantes das cidades de RO? 

df_mergeados = pd.merge(acidentes_ro, localidades_ro, on='chv_localidade', how='left')
df_agrupado = df_mergeados.groupby('municipio').agg({
    'num_acidente': 'count', 
    'qtde_habitantes': 'mean'
})
df_agrupado.assign(
    media_acidentes_mil_habitantes = lambda x: (x['num_acidente'] / x['qtde_habitantes']) * 1000
).sort_values(by='media_acidentes_mil_habitantes', ascending=False)

,num_acidente,qtde_habitantes,media_acidentes_mil_habitantes
municipio,,,
VILHENA,1330,105437.851128,12.614066
ROLIM DE MOURA,696,55491.074713,12.542558
CACOAL,971,86024.110196,11.287533
PIMENTA BUENO,405,36924.441975,10.968344
JI-PARANA,1374,130621.702329,10.518926
PORTO VELHO,5592,551761.150215,10.134820
JARU,449,50868.345212,8.826707
ARIQUEMES,966,111442.517598,8.668146
PRIMAVERA DE RONDONIA,22,2587.045455,8.503909
SANTA LUZIA D OESTE,47,5636.787234,8.338083
ESPIGAO D OESTE,266,32944.338346,8.074225
CEREJEIRAS,127,15833.259843,8.021090
ALTA FLORESTA D OESTE,174,22082.781609,7.879442
CORUMBIARA,53,6845.641509,7.742152
OURO PRETO DO OESTE,263,34855.726236,7.545389
ALVORADA D OESTE,94,13438.840426,6.994651
COLORADO DO OESTE,102,14772.911765,6.904529
SAO MIGUEL DO GUAPORE,158,22992.854430,6.871700
ITAPUA DO OESTE,71,10863.521127,6.535634
PRESIDENTE MEDICI,115,17597.739130,6.534930
SAO FELIPE D OESTE,31,4822.419355,6.428309
TEIXEIROPOLIS,25,4073.360000,6.137439
PIMENTEIRAS DO OESTE,12,2094.333333,5.729747
NOVO HORIZONTE DO OESTE,44,7858.727273,5.598871
THEOBROMA,54,10208.314815,5.289806
CANDEIAS DO JAMARI,143,28389.552448,5.037064
CHUPINGUAIA,56,11863.875000,4.720212
NOVA BRASILANDIA D OESTE,95,20290.810526,4.681922
SAO FRANCISCO DO GUAPORE,99,21212.292929,4.667105
NOVA UNIAO,31,6684.709677,4.637449
ALTO ALEGRE DOS PARECIS,59,13135.389831,4.491682
CABIXI,22,4918.772727,4.472660
MIRANTE DA SERRA,46,10480.673913,4.389031
MACHADINHO D OESTE,175,42058.017143,4.160919
SERINGUEIRAS,47,11732.063830,4.006115
GUAJARA-MIRIM,185,46789.994595,3.953837
CASTANHEIRAS,11,2853.727273,3.854608
VALE DO PARAISO,24,6306.250000,3.805748
ALTO PARAISO,82,22391.524390,3.662100
RIO CRESPO,14,3838.857143,3.646919
MONTE NEGRO,57,16130.824561,3.533607
BURITIS,143,41245.937063,3.467008
URUPA,37,10853.891892,3.408915
CUJUBIM,93,27724.397849,3.354446
GOVERNADOR JORGE TEIXEIRA,22,6714.772727,3.276358
MINISTRO ANDREAZZA,30,9274.433333,3.234699
COSTA MARQUES,60,19438.550000,3.086650
VALE DO ANARI,32,11579.750000,2.763445
NOVA MAMORE,82,32560.024390,2.518426
PARECIS,15,6369.266667,2.355059
CAMPO NOVO DE RONDONIA,21,14347.476190,1.463672
CACAULANDIA,9,6284.444444,1.432107

In [67]:
# Construa um mapa e faça o plot de cada acidente de 2022 considerando a sua latitude e longitude.